application: windstats
version: 1
runtime: python27
api_version: 1
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 800ms
  max_pending_latency: 800ms
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /
  script: topwebsite.app

- url: /windhistory
  script: windhistory.app

- url: /windrose
  script: windrose.app

- url: /windtable
  script: windtable.app

- url: /allhistory
  script: allhistory.app

- url: /faq
  script: faq.app

- url: /shorttermforecast
  script: shorttermforecast.app

- url: /winddump
  script: winddump.app

- url: /getwindspeed
  script: getwindspeed.app

- url: /tasks/updateweatherdb
  script: updateweatherdb.app
  login: admin

- url: /tasks/updateweatherdb_crotoy
  script: updateweatherdb_crotoy.app
  login: admin

- url: /tasks/checkweatherdb
  script: checkweatherdb.app
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static


libraries:
- name: matplotlib
  version: latest
- name: numpy
  version: latest

